defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: hopper_hop
goal_space: simplified_hopper
append_goal_to_observation: True
uncertainty: True
eval_every_frames: 100000
use_wandb: false
seed: 10
experiment: test_hopper
discount: 0.98
num_train_frames: 1000010
replay_buffer_episodes: 1000

agent:
  batch_size: 256
  z_dim: 50
  num_inference_steps: 10000
  myopic: true
  sampling: true
num_eval_episodes: 30
eval: true
load_model: /home/nuria/phd/controllable_agent/fbee_cluster/hopper/15/models/latest.pt
save_video: true
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
