defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: walker_walk
# custom_reward: walker_flip
goal_space: simplified_walker
append_goal_to_observation: True
uncertainty: True
eval_every_frames: 10000
use_wandb: false
warmup: false
seed: 0
experiment: test_walker
discount: 0.98
agent:
  batch_size: 256
  z_dim: 50
num_eval_episodes: 10
eval: true
load_model: /home/nuria/cluster/project/hilliges/nuriaa/results_clus/online_fb_walker_walk/1/models/latest.pt
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 400
    nodes: 1
    submitit_folder: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}/.slurm
    partition: learnlab # devlab learnlab
