defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: quadruped_stand
goal_space: simplified_quadruped_vel
append_goal_to_observation: True
uncertainty: True
eval_every_frames: 10000
use_wandb: false
seed: 0
experiment: eval_quadruped_stand
discount: 0.98
agent:
  batch_size: 256
  z_dim: 50
  sampling: True
num_eval_episodes: 30
eval: true
save_video: true
load_model: /home/nuria/phd/controllable_agent/fbee_cluster/quadruped/6/models/latest.pt
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
