defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: point_mass_maze_reach_bottom_right
custom_reward: maze_multi_goal
goal_space: simplified_point_mass_maze
append_goal_to_observation: false

uncertainty: True
eval_every_frames: 100000
use_wandb: false
warmup: false
seed: 0
experiment: test_correls
agent:
  batch_size: 256
  z_dim: 100
  num_inference_steps: 10000
  mix_ratio: 0.3
  add_trunk: true # I think! check G2 appendix paper
  sampling: True
  update_z_every_step: 100
  update_z_proba: 1.
  myopic: True
  num_z_samples: 100
  num_obs_samples: 1000
  rnd_coeff: 0.5
  rnd: False
  rnd_embed_dim: 100
num_eval_episodes: 10
load_model: /home/nuria/phd/controllable_agent/fbee_cluster/maze3/18/models/latest.pt
eval: true
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
  # launcher:
  #   timeout_min: 4300
  #   cpus_per_task: 10
  #   gpus_per_node: 1
  #   tasks_per_node: 1
  #   mem_gb: 400
  #   nodes: 1
  #   submitit_folder: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}/.slurm
  #   partition: learnlab # devlab learnlab
