defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_

# used with train_offline.py and withouth load_replay buffer!
task: point_mass_maze_reach_bottom_right
goal_space: simplified_point_mass_maze
replay_buffer_episodes: 1000 # how much episodes use from the 'expl_agent' buffer
expl_agent: rnd
custom_reward: maze_multi_goal
append_goal_to_observation: false
uncertainty: False
eval_every_steps: 10000
use_wandb: true
warmup: false
seed: 0
experiment: offline_maze
discount: 0.99
num_grad_steps: 1000000

agent:
  batch_size: 256
  z_dim: 100
  num_inference_steps: 10000
  mix_ratio: 0.3
  add_trunk: True

num_eval_episodes: 30
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
