defaults:
  - workspace_config # this is to load the config in pretrain.py
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: cheetah_walk_backward
custom_reward: cheetah_walk_backward
uncertainty: True
eval_every_frames: 10000
use_wandb: false
warmup: false
seed: 0
experiment: test_cheetah
discount: 0.98
agent:
  batch_size: 256
  z_dim: 50
num_eval_episodes: 10
eval: true
load_model: /home/nuria/cluster/project/hilliges/nuriaa/results_clus/online_fb_cheetah/4/models/latest.pt
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
