defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: point_mass_maze_reach_bottom_right
custom_reward: maze_multi_goal
goal_space: simplified_point_mass_maze
uncertainty: True
eval_every_frames: 100000
use_wandb: true
warmup: false
seed: 0
experiment: online_track_disagr
discount: 0.99
num_train_frames: 2000010

agent:
  batch_size: 256
  z_dim: 100
  num_inference_steps: 10000
  mix_ratio: 0.5
num_eval_episodes: 10
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
