defaults:
  - workspace_config
  - agent: fb_ddpg
  - override hydra/launcher: submitit_slurm
  - _self_


task: quadruped_walk
goal_space: simplified_quadruped_velx
append_goal_to_observation: True
uncertainty: True
eval_every_frames: 10000
use_wandb: true
warmup: false
seed: 0
experiment: test_quadruped
discount: 0.98
num_train_frames: 2000010

agent:
  batch_size: 256
  z_dim: 50
  num_inference_steps: 10000
  mix_ratio: 0.5
num_eval_episodes: 10
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: ./exp_paper/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}
